name: Chollometro 300 Grados
on:
  schedule:
    - cron: '*/10 * * * *' # Se ejecuta cada 10 minutos
  workflow_dispatch: # Botón para probar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # Actualizado de v3 a v4

      - name: Setup Python
        uses: actions/setup-python@v5 # Actualizado de v4 a v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install feedparser requests

      - name: Run Bot
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: python bot.py

      - name: Save Cache
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add vistos.txt
          # El '|| exit 0' evita que el proceso falle si no hay nuevos chollos que guardar
          git commit -m "Actualizar historial de chollos [skip ci]" || exit 0
          git push
