name: Chollometro Prueba
on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true 

# ¡ESTO ES NUEVO Y NECESARIO PARA HACER EL PUSH!
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install feedparser requests

      - name: Run Bot
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: python bot.py

      - name: Save Cache
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add vistos.txt
          git commit -m "Actualizar historial [skip ci]" || exit 0
          git push
